### PR TITLE
fixed upgrade to kube 1.24

### PR DESCRIPTION
**Pull request by raffaelespazzoli**
fixed upgrade to kube 1.24
Signed-off-by: raffaelespazzoli <raffaele.spazzoli@gmail.com>

### CODE REVIEW

**Comment by raffaelespazzoli** [comment]
fixes #43

**Review by sabre1041 — APPROVED** [review]
LGTM

**Review by sabre1041 — APPROVED** [review]
LGTM

**Review by sabre1041 — APPROVED** [review]
LGTM

**Review by sabre1041 — APPROVED** [review]
LGTM

**Pull request merged**
